# Database container for running tests locally.
version: '2'

services:
  trading-svc:
    container_name: database-common-db
    image: postgres:11.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
