version: "3.1"

services:
  mysql-57:
    container_name: mysql-57
    image: mysql:5.7
    command: --lower_case_table_names=1
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
     # MYSQL_ROOT_PASSWORD: 'test_pass'
     # MYSQL_USER: 'test'
     # MYSQL_PASS: 'pass'
    ports:
      - "3306:3306"
#Post Migration of Docker-Desktop ( volumn mounting is not working with Comlina ) 
#    volumes:
#      - $HOME/DATABASE_DIR/MYSQL_DATA_DIR/mysql-57:/var/lib/mysql

